dist: xenial
language: generic

before_install:
  - pyenv versions
  - pyenv global 3.6.7

install:
  - pip install -r requirements.txt
  - yarn install

script:
  - cp config.yml.example config.yml
  - yarn run heroku-postbuild
  - flask routes
  - flask db upgrade